spring:
  application:
    name: hanghae-excercise

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        permittedNumberOfCallsInHalfOpenState: 4
        maxWaitDurationInHalfOpenState: 1000
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
    instances:
      customCircuitBreaker:
        baseConfig: default
